---
version: "3.6"
services:

  assembly:
    build: ./assembly
    image: assembly
    volumes:
      - artifact:/source/target

  prod:
    build: ./prod
    image: prod
    ports:
      - 50:8080
    volumes:
      - artifact:/var/lib/tomcat9/webapps

volumes:
  artifact: