---
version: "3.6"
services:

  build:
    build: ./build
    image: build
    volumes:
      - artifact:/source/target

  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      # MYSQL_ROOT_PASSWORD: jsjhdaksjhkdaskjadhsdhb
      MYSQL_DATABASE: dd
      MYSQL_USER: acp4pogynvaeidfj
      MYSQL_PASSWORD: jc31d2qyy7h9jv5jn1u9uosjksxzaizw
    ports:
      - 3306:3306
      - 33060:33060
    volumes:
      - dbvolume:/var/lib/mysql

  prod:
    build: ./prod
    image: prod
    ports:
      - 80:8080
    volumes:
      - artifact:/usr/local/tomcat/webapps
    depends_on:
      - build
      - db

volumes:
  artifact:
  dbvolume: